// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function RobotEnable() {
  return window['go']['main']['App']['RobotEnable']();
}

export function RobotToggle(arg1) {
  return window['go']['main']['App']['RobotToggle'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
