// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.GuiConfig>;

export function RobotEnable():Promise<boolean>;

export function RobotToggle(arg1:boolean):Promise<void>;

export function SetConfig(arg1:config.GuiConfig):Promise<void>;
